# -*- coding: utf-8 -*-
"""-untitled0-py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/NizomjonOlimjonov24/7edd4af030cf59bafb51893dab0cc81f/-untitled0-py.ipynb
"""



import numpy as np

#1. Massiv yaratish

# Bu nizomjoni ishi

array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

#2. Matematik operatsiyalar
sum_array = np.sum(array_ld)
mean_array = np.mean(array_1d)
product_array = np.prod(array_1d)

print("1D Massiv: ", array_ld)

print("2D Massiv:\n", array_2d)

print("Sum of arrays: ", sum_array)

print("Maximum: ", mean_array)

print("Multiplication: ", product_array)