# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GChjhzF3DOEXxIRC8lDj8FwixLHlMkeJ
"""

import pandas as pd
guruh=pd.DataFrame({
    "Familiya":['Qadamova','Xalilov','Abdullayeva','Jorayeva','Rahmatov' ],
    "Ismi":['Zulayho','Durbek','Mohigul','Gulruxsor','Rasuljon' ],
    "Fani":['Suniy intelekt asoslari','Suniy intelekt asoslari','Malumotlar tuzilmasi va algoritimlar' ],
})
print(guruh)